### ISSUE TITLE
Feature request- action bar messages 

### ISSUE THREAD

**Issue by RhythmicSys** [12emin34/MoreMouseKeybinds#1]
It would be helpful to have an action bar message or something similar available to pop up when the toggles are used :3

**Comment by 12emin34** [comment]
bruh, I'm just now noticing this, guess I need to setup some kind of push notifications. Will make a new release asap lol

**Comment by 12emin34** [comment]
added in https://github.com/12emin34/MoreMouseKeybinds/commit/f92c0f9f6b113e0870cc5ec441b1e290082f2e34
