### ISSUE TITLE
Very low quality icon.png

### ISSUE THREAD

**Issue by Dronatar** [12emin34/MoreMouseKeybinds#3]
MoreMouseKeybinds-1.3.1 icon.png (6KiB): 
![old_icon](https://user-images.githubusercontent.com/35381259/220464667-d141a382-5c0c-42c1-aa47-a39ba77286c1.png)![ScreenShot_20230221235112](https://user-images.githubusercontent.com/35381259/220466785-ed2ec2e2-3d02-45a4-bb7a-f58aef1ff64e.png)

New icon.png (12KiB):
![icon](https://user-images.githubusercontent.com/35381259/220468469-fb17b982-7836-4be0-a16d-443efbf6b1d4.png)![ScreenShot_20230221235831](https://user-images.githubusercontent.com/35381259/220468077-d176f8ee-58c8-4a58-be9f-4e30bd934f7f.png)

**Comment by 12emin34** [comment]
I resized the icon.png file to reduce filesize as it was around 900KB before, didn't realize it would get this low quality though. Thank you so much for this, gonna use it :).

**Comment by 12emin34** [comment]
fixed in https://github.com/12emin34/MoreMouseKeybinds/commit/f071f39249acd1b57fd921131b70dc61d22ef12b
